/* ---------- SPECIES (2024) ---------- */
const SPECIES = [
  {id:'humano', name:'Humano', size:'Mediano', speed:30,
    traits:['Competente: dominas una habilidad a tu elección','Ingenioso: descanso corto adicional una vez por descanso largo']},
  {id:'elfo', name:'Elfo', size:'Mediano', speed:30,
    traits:['Visión en la oscuridad 18 m','Linaje feérico: ventaja contra hechizado, inmune a dormir mágico','Trance (4h en vez de 8h)','Linaje (Alto/Bosque/Oscuro) a elegir']},
  {id:'enano', name:'Enano', size:'Mediano', speed:30,
    traits:['Visión en la oscuridad 36 m','Resiliencia enana: resistencia a veneno, ventaja contra envenenado','Robustez enana: +1 PG por nivel','Afinidad con piedra']},
  {id:'mediano', name:'Mediano (Halfling)', size:'Pequeño', speed:30,
    traits:['Suerte: puedes repetir un 1 en d20','Valentía: ventaja contra asustado','Sigilo natural: puedes esconderte tras criaturas Grandes+']},
  {id:'gnomo', name:'Gnomo', size:'Pequeño', speed:30,
    traits:['Visión en la oscuridad 18 m','Astucia gnoma: ventaja en salvaciones de Int/Sab/Car contra magia']},
  {id:'draconido', name:'Dracónido', size:'Mediano', speed:30,
    traits:['Aliento de dragón (línea o cono, según ascendencia)','Resistencia al daño de tu ascendencia','A nivel 5: breve vuelo al usar el aliento']},
  {id:'semiorco', name:'Orco', size:'Mediano', speed:30,
    traits:['Visión en la oscuridad 36 m','Resistencia implacable: vuelve a 1 PG una vez por descanso largo','Instinto de cazador: ventaja en Percepción, Supervivencia o Intimidación']},
  {id:'tiefling', name:'Tiefling', size:'Mediano', speed:30,
    traits:['Visión en la oscuridad 18 m','Resistencia al daño de fuego','Legado infernal: hechizos menores según linaje (Abisal/Ctónico/Infernal)']},
  {id:'aasimar', name:'Aasimar', size:'Mediano', speed:30,
    traits:['Visión en la oscuridad 18 m','Curación celestial: los conjuros de curación sobre ti curan de más','A nivel 3: Revelación Celestial (transformación)']},
  {id:'goliat', name:'Goliat', size:'Mediano', speed:35,
    traits:['Ascendencia gigante (rasgo aleatorio: Piedra/Fuego/Hielo/Nube/Tormenta/Fuego interior)','Aguante poderoso: reduce daño una vez por descanso corto']},
];

/* ---------- BACKGROUNDS (2024) — dan el ajuste de característica ---------- */
const BACKGROUNDS = [
  {id:'acolito', name:'Acólito', abilities:['int','wis','cha'], skills:['Perspicacia','Religión'], tool:'Kit de calígrafo', feat:'Iniciado en la Magia (clérigo)'},
  {id:'artista', name:'Artista', abilities:['str','dex','cha'], skills:['Acrobacias','Interpretación'], tool:'Instrumento musical', feat:'Intérprete'},
  {id:'artesano', name:'Artesano Gremial', abilities:['str','dex','int'], skills:['Perspicacia','Persuasión'], tool:'Herramientas de artesano', feat:'Iniciado Mágico (mago)'},
  {id:'campesino', name:'Campesino', abilities:['str','con','wis'], skills:['Trato con Animales','Supervivencia'], tool:'Herramientas de carpintero', feat:'Resistente'},
  {id:'criminal', name:'Criminal', abilities:['dex','con','int'], skills:['Engaño','Sigilo'], tool:'Herramientas de ladrón', feat:'Iniciado Mágico (embaucador)'},
  {id:'ermitaño', name:'Ermitaño', abilities:['con','wis','cha'], skills:['Medicina','Religión'], tool:'Kit de herbolario', feat:'Curandero'},
  {id:'erudito', name:'Erudito', abilities:['int','wis','cha'], skills:['Arcanos','Historia'], tool:'Kit de calígrafo', feat:'Iniciado Mágico (mago)'},
  {id:'forastero', name:'Forastero', abilities:['str','dex','wis'], skills:['Atletismo','Supervivencia'], tool:'Herramientas de artesano', feat:'Iniciativo'},
  {id:'granjero', name:'Granjero', abilities:['str','con','wis'], skills:['Trato con Animales','Naturaleza'], tool:'Herramientas de carpintero', feat:'Robusto'},
  {id:'guardia', name:'Guardia', abilities:['str','dex','wis'], skills:['Atletismo','Percepción'], tool:'Juego de dados', feat:'Alerta'},
  {id:'guia', name:'Guía', abilities:['dex','con','wis'], skills:['Sigilo','Supervivencia'], tool:'Herramientas de cartógrafo', feat:'Iniciativo'},
  {id:'marinero', name:'Marinero', abilities:['str','dex','wis'], skills:['Acrobacias','Percepción'], tool:'Herramientas de navegante', feat:'Con Suerte'},
  {id:'mercader', name:'Mercader', abilities:['con','int','cha'], skills:['Perspicacia','Persuasión'], tool:'Herramientas de mercader', feat:'Negociador'},
  {id:'noble', name:'Noble', abilities:['str','int','cha'], skills:['Historia','Persuasión'], tool:'Juego de dados', feat:'Afortunado'},
  {id:'sabio', name:'Sabio', abilities:['con','int','wis'], skills:['Arcanos','Historia'], tool:'Kit de calígrafo', feat:'Mago Aprendiz'},
  {id:'soldado', name:'Soldado', abilities:['str','dex','con'], skills:['Atletismo','Intimidación'], tool:'Juego de dados', feat:'Con Suerte'},
];

/* ---------- CLASSES (2024) ---------- */
const CLASSES = [
  {id:'barbaro', name:'Bárbaro', hitDie:12, primary:['str','con'], saves:['str','con'], caster:null, armor:'ninguna (Defensa sin Armadura)',
    subclasses:['Senda del Berserker','Senda del Corazón Salvaje','Senda del Árbol del Mundo','Senda del Fanático']},
  {id:'bardo', name:'Bardo', hitDie:8, primary:['cha','dex'], saves:['dex','cha'], caster:'full', casterAbility:'cha', casterType:'known', armor:'ligera',
    subclasses:['Colegio de la Danza','Colegio del Glamour','Colegio del Saber','Colegio del Valor']},
  {id:'clerigo', name:'Clérigo', hitDie:8, primary:['wis','con'], saves:['wis','cha'], caster:'full', casterAbility:'wis', casterType:'prepared', armor:'media + escudo',
    subclasses:['Dominio de la Vida','Dominio de la Luz','Dominio del Engaño','Dominio de la Guerra']},
  {id:'druida', name:'Druida', hitDie:8, primary:['wis','con'], saves:['int','wis'], caster:'full', casterAbility:'wis', casterType:'prepared', armor:'ligera (no metal)',
    subclasses:['Círculo de la Tierra','Círculo de la Luna','Círculo del Mar','Círculo de las Estrellas']},
  {id:'guerrero', name:'Guerrero', hitDie:10, primary:['str','dex'], saves:['str','con'], caster:null, armor:'pesada + escudo',
    subclasses:['Maestro de Batalla','Campeón','Caballero Arcano','Guerrero Psíquico']},
  {id:'monje', name:'Monje', hitDie:8, primary:['dex','wis'], saves:['str','dex'], caster:null, armor:'ninguna (Defensa sin Armadura)',
    subclasses:['Guerrero de la Misericordia','Guerrero de la Sombra','Guerrero de los Elementos','Guerrero de la Mano Abierta']},
  {id:'paladin', name:'Paladín', hitDie:10, primary:['str','cha'], saves:['wis','cha'], caster:'half', casterAbility:'cha', casterType:'prepared', armor:'pesada + escudo',
    subclasses:['Juramento de los Ancianos','Juramento de Devoción','Juramento de Gloria','Juramento de Venganza']},
  {id:'explorador', name:'Explorador (Ranger)', hitDie:10, primary:['dex','wis'], saves:['str','dex'], caster:'half', casterAbility:'wis', casterType:'prepared', armor:'media',
    subclasses:['Maestro de Bestias','Vagabundo Feérico','Acechador del Ocaso','Cazador']},
  {id:'picaro', name:'Pícaro', hitDie:8, primary:['dex','int'], saves:['dex','int'], caster:null, armor:'ligera',
    subclasses:['Truhan Arcano','Asesino','Alma-Cuchilla','Ladrón']},
  {id:'hechicero', name:'Hechicero', hitDie:6, primary:['cha','con'], saves:['con','cha'], caster:'full', casterAbility:'cha', casterType:'known', armor:'ninguna',
    subclasses:['Hechicería Aberrante','Hechicería de Relojería','Hechicería Dracónica','Hechicería de Magia Salvaje']},
  {id:'brujo', name:'Brujo (Warlock)', hitDie:8, primary:['cha','con'], saves:['wis','cha'], caster:'pact', casterAbility:'cha', casterType:'known', armor:'ligera',
    subclasses:['Pacto del Archihada','Pacto del Celestial','Pacto del Diablo','Pacto del Viejo Ente']},
  {id:'mago', name:'Mago', hitDie:6, primary:['int','con'], saves:['int','wis'], caster:'full', casterAbility:'int', casterType:'prepared', armor:'ninguna',
    subclasses:['Escuela de Abjuración','Escuela de Adivinación','Escuela de Evocación','Escuela de Ilusión']},
];

/* prioridad completa de las 6 características por clase, de más a menos relevante para el reparto de estadísticas */
const STATPRIORITY = {
  barbaro:   ['str','con','dex','wis','cha','int'],
  bardo:     ['cha','dex','con','wis','int','str'],
  clerigo:   ['wis','con','str','cha','dex','int'],
  druida:    ['wis','con','dex','int','cha','str'],
  guerrero:  ['str','con','dex','wis','cha','int'],
  monje:     ['dex','wis','con','str','cha','int'],
  paladin:   ['str','cha','con','wis','dex','int'],
  explorador:['dex','wis','con','str','cha','int'],
  picaro:    ['dex','int','con','wis','cha','str'],
  hechicero: ['cha','con','dex','wis','int','str'],
  brujo:     ['cha','con','dex','wis','int','str'],
  mago:      ['int','con','dex','wis','cha','str'],
};

/* ---------- spell slot tables ---------- */
const FULLCASTERSLOTS = {
  1:[2,0,0,0,0,0,0,0,0], 2:[3,0,0,0,0,0,0,0,0], 3:[4,2,0,0,0,0,0,0,0], 4:[4,3,0,0,0,0,0,0,0],
  5:[4,3,2,0,0,0,0,0,0], 6:[4,3,3,0,0,0,0,0,0], 7:[4,3,3,1,0,0,0,0,0], 8:[4,3,3,2,0,0,0,0,0],
  9:[4,3,3,3,1,0,0,0,0], 10:[4,3,3,3,2,0,0,0,0], 11:[4,3,3,3,2,1,0,0,0], 12:[4,3,3,3,2,1,0,0,0],
  13:[4,3,3,3,2,1,1,0,0], 14:[4,3,3,3,2,1,1,0,0], 15:[4,3,3,3,2,1,1,1,0], 16:[4,3,3,3,2,1,1,1,0],
  17:[4,3,3,3,2,1,1,1,1], 18:[4,3,3,3,3,1,1,1,1], 19:[4,3,3,3,3,2,1,1,1], 20:[4,3,3,3,3,2,2,1,1],
};
const HALFCASTERSLOTS = {
  1:[0,0,0,0,0], 2:[2,0,0,0,0], 3:[3,0,0,0,0], 4:[3,0,0,0,0], 5:[4,2,0,0,0], 6:[4,2,0,0,0],
  7:[4,3,0,0,0], 8:[4,3,0,0,0], 9:[4,3,2,0,0], 10:[4,3,2,0,0], 11:[4,3,3,0,0], 12:[4,3,3,0,0],
  13:[4,3,3,1,0], 14:[4,3,3,1,0], 15:[4,3,3,2,0], 16:[4,3,3,2,0], 17:[4,3,3,3,1], 18:[4,3,3,3,1],
  19:[4,3,3,3,2], 20:[4,3,3,3,2],
};
const PACTSLOTS = { // [nº de espacios, nivel del espacio]
  1:[1,1],2:[2,1],3:[2,2],4:[2,2],5:[2,3],6:[2,3],7:[2,4],8:[2,4],9:[2,5],10:[2,5],
  11:[3,5],12:[3,5],13:[3,5],14:[3,5],15:[3,5],16:[3,5],17:[4,5],18:[4,5],19:[4,5],20:[4,5],
};

/* curated spell pool: {level: [name,...]} shared, filtered lightly by flavor per class via SPELL_FLAVOR */
const SPELL_POOL = {
  0:[
    {name:'Taumaturgia',desc:'Genera pequeños efectos sobrenaturales: voz atronadora, puertas que se abren solas, luces parpadeantes.',range:'9 m',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Prestidigitación',desc:'Truco de magia menor: crea una chispa, un olor, limpia o ensucia un objeto pequeño.',range:'3 m',concentration:false,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Luz',desc:'Hace que un objeto emita luz brillante en un radio de 6 metros durante 1 hora.',range:'Toque',concentration:false,damage:null,duration:'1 hora',cast:'1 acción'},
    {name:'Mano de Mago',desc:'Crea una mano espectral que manipula objetos ligeros a distancia.',range:'9 m',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Reparar',desc:'Repara una rotura o daño menor en un objeto no mágico.',range:'Toque',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Escupir Ácido',desc:'Lanza una salpicadura de ácido que daña a una o dos criaturas cercanas.',range:'18 m',concentration:false,damage:'1d6 ácido',duration:'Instantáneo',cast:'1 acción'},
    {name:'Descarga Eléctrica',desc:'Un rayo de electricidad hace un chasquido y daña al objetivo con desventaja adicional a su siguiente ataque.',range:'Toque',concentration:false,damage:'1d8 eléctrico',duration:'Instantáneo',cast:'1 acción'},
    {name:'Rayo de Escarcha',desc:'Un dardo de hielo daña y reduce la velocidad del objetivo.',range:'18 m',concentration:false,damage:'1d8 frío',duration:'Instantáneo',cast:'1 acción'},
    {name:'Fuego Fatuo',desc:'Crea una luz flotante que puede usarse para distraer o guiar en la oscuridad.',range:'18 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Vapor Ardiente',desc:'Lanza un dardo de fuego a distancia que aumenta de daño con el nivel.',range:'36 m',concentration:false,damage:'1d10 fuego',duration:'Instantáneo',cast:'1 acción'},
    {name:'Sagrada Llama',desc:'Fuego divino cae sobre el objetivo, que debe salvar o sufrir daño radiante.',range:'18 m',concentration:false,damage:'1d8 radiante',duration:'Instantáneo',cast:'1 acción'},
    {name:'Gota Curativa',desc:'Truco menor de curación: restaura un puñado de puntos de golpe al tocar a la criatura.',range:'Toque',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Golpe de Guía',desc:'Otorga un bonificador a la siguiente tirada de ataque de un aliado.',range:'9 m',concentration:true,damage:null,duration:'Hasta 1 turno',cast:'1 acción adicional'},
    {name:'Espina de Vid',desc:'Una zarza mágica hiere y ralentiza a la criatura tocada.',range:'9 m',concentration:false,damage:'1d6 perforante',duration:'Instantáneo',cast:'1 acción'},
    {name:'Ilusión Menor',desc:'Crea un sonido o imagen ilusoria sin sustancia física.',range:'9 m',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Percepción a Distancia',desc:'Proyecta tu vista y oído a un punto cercano invisible.',range:'9 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Andanada Feérica',desc:'Un rayo crepitante de energía que empuja al objetivo si impacta.',range:'36 m',concentration:false,damage:'1d10 fuerza',duration:'Instantáneo',cast:'1 acción'},
    {name:'Toque Gélido',desc:'Un espectro esquelético golpea al objetivo con frío necrótico y le impide curarse.',range:'36 m',concentration:false,damage:'1d8 necrótico',duration:'Hasta tu siguiente turno',cast:'1 acción'},
    {name:'Luces Danzantes',desc:'Crea hasta cuatro luces flotantes que puedes mover y combinar en una silueta tenue.',range:'36 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Artesanía Druídica',desc:'Crea pequeños efectos naturales: flores, hielo, viento suave, olores del bosque.',range:'9 m',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Truco Menor de Bardo',desc:'Un efecto sonoro o visual menor con sabor artístico, útil para distraer o entretener.',range:'18 m',concentration:false,damage:'1d4 psíquico',duration:'Instantáneo',cast:'1 acción'},
    {name:'Guardia Espectral',desc:'Un aullido espectral asusta brevemente a quien te ataca cuerpo a cuerpo.',range:'Personal',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Chispa de Fuego Verde',desc:'Una chispa que salta entre dos objetivos cercanos causando daño de fuego.',range:'Toque (arma)',concentration:false,damage:'1d4 fuego',duration:'Instantáneo',cast:'1 acción'},
    {name:'Sonido Fantasma',desc:'Reproduce un sonido ilusorio, desde un susurro hasta un grito, a distancia.',range:'18 m',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Baile de Llamas',desc:'Hace bailar una llama existente, iluminando y entreteniendo sin causar daño.',range:'9 m',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Aguijón de Escarcha',desc:'Un pequeño dardo helado que causa daño frío y deja la piel entumecida.',range:'18 m',concentration:false,damage:'1d6 frío',duration:'Instantáneo',cast:'1 acción'},
    {name:'Custodia de la Tumba',desc:'Un susurro fúnebre asusta a los no-muertos que se acercan a un área protegida.',range:'18 m',concentration:false,damage:'1d8 necrótico (solo no-muertos)',duration:'Instantáneo',cast:'1 acción'},
    {name:'Estática',desc:'Genera electricidad estática que puede sobrecargar objetos metálicos pequeños.',range:'Toque',concentration:false,damage:'1d4 eléctrico',duration:'Instantáneo',cast:'1 acción'},
  ],
  1:[
    {name:'Curar Heridas',desc:'Restaura puntos de golpe a una criatura tocada.',range:'Toque',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Escudo',desc:'Reacción que otorga +5 a la CA hasta tu siguiente turno y bloquea proyectiles mágicos.',range:'Personal',concentration:false,damage:null,duration:'Hasta tu siguiente turno',cast:'1 reacción'},
    {name:'Proyectil Mágico',desc:'Tres dardos de fuerza que impactan automáticamente, repartibles entre objetivos.',range:'36 m',concentration:false,damage:'3×(1d4+1) fuerza',duration:'Instantáneo',cast:'1 acción'},
    {name:'Palabra de Curación',desc:'Cura a distancia con una sola palabra, como acción adicional.',range:'18 m',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción adicional'},
    {name:'Detectar Magia',desc:'Sientes la presencia de magia en un radio de 9 metros durante 10 minutos.',range:'Personal (9 m)',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Hechizar Persona',desc:'Intenta encantar a un humanoide para que te vea como amigo de confianza.',range:'9 m',concentration:false,damage:null,duration:'1 hora',cast:'1 acción'},
    {name:'Sueño',desc:'Sume a varias criaturas cercanas en un sueño mágico, empezando por las de menos PG.',range:'18 m',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Bendición',desc:'Hasta tres criaturas añaden 1d4 a sus ataques y salvaciones.',range:'9 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Mando',desc:'Ordenas una palabra de una sílaba (huye, cae, suelta...) que el objetivo debe obedecer.',range:'18 m',concentration:false,damage:null,duration:'Hasta tu siguiente turno',cast:'1 acción'},
    {name:'Niebla Punzante',desc:'Crea una nube de vapor cortante que daña a las criaturas en su interior.',range:'18 m (radio 6 m)',concentration:false,damage:'2d6 cortante',duration:'Instantáneo',cast:'1 acción'},
    {name:'Marca del Cazador',desc:'Marcas a una presa: cada golpe le hace daño extra y puedes rastrearla.',range:'27 m',concentration:true,damage:'1d6 extra por golpe',duration:'Hasta 1 hora',cast:'1 acción adicional'},
    {name:'Fiel Escudero',desc:'Invocas un espíritu servicial con forma de animal que ayuda en tareas menores.',range:'9 m',concentration:false,damage:null,duration:'Hasta que se disipa',cast:'1 hora'},
    {name:'Absorber Elementos',desc:'Reacción que reduce el daño elemental recibido y lo devuelve en tu siguiente golpe.',range:'Personal',concentration:false,damage:null,duration:'Hasta tu siguiente turno',cast:'1 reacción'},
    {name:'Salto',desc:'Triplica la distancia de salto de la criatura tocada durante 1 minuto.',range:'Toque',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Disfrazarse',desc:'Cambia tu apariencia (rasgos, ropa, voz) de forma ilusoria durante 1 hora.',range:'Personal',concentration:false,damage:null,duration:'1 hora',cast:'1 acción'},
    {name:'Detectar el Bien y el Mal',desc:'Sabes si hay celestiales, no-muertos, demonios o similares cerca.',range:'Personal (9 m)',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Manos Ardientes',desc:'Un cono de llamas quema a todas las criaturas frente a ti.',range:'Cono de 4,5 m',concentration:false,damage:'3d6 fuego',duration:'Instantáneo',cast:'1 acción'},
    {name:'Armadura de Mago',desc:'Establece una CA base protectora mientras no lleves armadura.',range:'Toque',concentration:false,damage:null,duration:'8 horas',cast:'1 acción'},
    {name:'Reprender Infernal',desc:'Reacción que castiga con fuego divino a quien te haya golpeado.',range:'18 m',concentration:false,damage:'2d10 fuego',duration:'Instantáneo',cast:'1 reacción'},
    {name:'Ayuda del Héroe',desc:'Otorga PG temporales, ventaja e inmunidad al miedo durante un tiempo.',range:'Toque',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Herir',desc:'Toque que causa graves heridas necróticas a la criatura afectada.',range:'Toque',concentration:false,damage:'3d10 necrótico',duration:'Instantáneo',cast:'1 acción'},
    {name:'Alarma',desc:'Protege una zona: te avisa mentalmente o con sonido si algo entra.',range:'9 m',concentration:false,damage:null,duration:'8 horas',cast:'1 minuto'},
    {name:'Compañero Animal',desc:'Invoca un espíritu con forma de bestia que lucha o explora por ti.',range:'9 m',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Gracia del Tigre',desc:'El objetivo gana ventaja en pruebas de Fuerza y puede embestir con fuerza extra.',range:'Toque',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Enredar',desc:'Zarzas mágicas atrapan y restringen a las criaturas en una zona.',range:'27 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Refugio Ilusorio',desc:'Crea una ilusión inmóvil (roca, puerta, matorral) para esconder u ocultar algo.',range:'18 m',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Palabra de Curación Sanadora',desc:'Variante rápida de curación a distancia, sin necesidad de tocar al objetivo.',range:'9 m',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción adicional'},
    {name:'Retirada Veloz',desc:'Aumenta tu velocidad y te da ventaja para escapar del combate.',range:'Personal',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'1 acción adicional'},
    {name:'Rayo Ácido',desc:'Un chorro de ácido causa daño inmediato y persistente por el resto del turno.',range:'27 m',concentration:false,damage:'2d4 ácido (+1d4 al final del turno)',duration:'Instantáneo',cast:'1 acción'},
    {name:'Detectar Trampas y Puertas',desc:'Revela pasadizos, puertas y trampas ocultas en el entorno cercano.',range:'9 m',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
  ],
  2:[
    {name:'Rayo Abrasador',desc:'Dos rayos de fuego que puedes dirigir contra uno o dos objetivos.',range:'36 m',concentration:false,damage:'2×2d6 fuego',duration:'Instantáneo',cast:'1 acción'},
    {name:'Telaraña',desc:'Llena una zona de telarañas pegajosas que restringen el movimiento.',range:'18 m',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Invisibilidad',desc:'Vuelve invisible a una criatura tocada hasta que ataque o conjure.',range:'Toque',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Sordoceguera',desc:'Ciega o ensordece al objetivo, según elijas.',range:'9 m',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Ayuda',desc:'Otorga puntos de golpe temporales y aumenta el máximo de PG por un tiempo.',range:'9 m',concentration:false,damage:null,duration:'8 horas',cast:'1 acción'},
    {name:'Restablecimiento Menor',desc:'Cura una enfermedad o elimina una condición como el envenenamiento.',range:'Toque',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Arma Espiritual',desc:'Invoca un arma espectral que ataca por ti como acción adicional.',range:'18 m',concentration:false,damage:'1d8 fuerza',duration:'1 minuto',cast:'1 acción adicional'},
    {name:'Escudo de Fe',desc:'Un campo protector otorga +2 a la CA de la criatura elegida.',range:'18 m',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'1 acción adicional'},
    {name:'Niebla Oscura',desc:'Crea una esfera de oscuridad mágica que ni siquiera la visión en la oscuridad atraviesa.',range:'18 m',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Ver Invisible',desc:'Te permite ver criaturas y objetos invisibles durante 1 hora.',range:'Personal',concentration:false,damage:null,duration:'1 hora',cast:'1 acción'},
    {name:'Golpe del Trueno',desc:'Un estruendo daña y empuja a la criatura tocada.',range:'Toque',concentration:false,damage:'2d8 trueno',duration:'Instantáneo',cast:'1 acción'},
    {name:'Ráfaga de Viento',desc:'Un muro de viento aparta proyectiles, gases y criaturas pequeñas.',range:'Personal (línea 18 m)',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Silencio',desc:'Ninguna criatura puede emitir sonido dentro de la zona afectada.',range:'36 m',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Sugerencia',desc:'Sugieres un curso de acción razonable que el objetivo se siente impulsado a seguir.',range:'9 m',concentration:true,damage:null,duration:'Hasta 8 horas',cast:'1 acción'},
    {name:'Levitar',desc:'Hace flotar a una criatura u objeto, controlando su altura a voluntad.',range:'18 m',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Zona de la Verdad',desc:'Las criaturas dentro no pueden mentir conscientemente.',range:'18 m',concentration:false,damage:null,duration:'10 minutos',cast:'1 acción'},
    {name:'Encantar Compañero',desc:'Mejora temporalmente el vínculo y las capacidades de tu compañero animal.',range:'Toque',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Pasos Fantasmales',desc:'Te vuelves incorpóreo por un instante y puedes moverte a través de objetos sólidos.',range:'Personal',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Nube Apestosa',desc:'Una nube de gas nauseabundo puede provocar náuseas incapacitantes.',range:'27 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Rayo de Debilitar',desc:'Reduce la fuerza física del objetivo, dificultando sus ataques y cargas.',range:'18 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Sanguijuela Espiritual',desc:'Un espíritu vinculado drena vida del objetivo mientras dura el conjuro.',range:'9 m',concentration:true,damage:'2d10 necrótico',duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Prosperar',desc:'Bendice una zona pequeña con crecimiento vegetal acelerado y beneficioso.',range:'45 m',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Reflejo del Espejo',desc:'Crea duplicados ilusorios de ti mismo que confunden a los atacantes.',range:'Personal',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Movimiento Acelerado',desc:'Duplica la velocidad del objetivo y le otorga ventaja en Acrobacias.',range:'Toque',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Puntería Certera',desc:'Aumenta la precisión de tus próximos disparos con proyectiles.',range:'Personal',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción adicional'},
    {name:'Encogimiento',desc:'Reduce el tamaño y la fuerza de una criatura durante varios minutos.',range:'9 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Toque del Vampiro',desc:'Drena vida de la víctima al tocarla y te cura la mitad del daño causado.',range:'Toque',concentration:true,damage:'3d6 necrótico',duration:'Hasta 1 minuto',cast:'1 acción'},
  ],
  3:[
    {name:'Bola de Fuego',desc:'Una esfera explota causando gran daño de fuego en área.',range:'45 m (radio 6 m)',concentration:false,damage:'8d6 fuego',duration:'Instantáneo',cast:'1 acción'},
    {name:'Contrahechizo',desc:'Reacción que interrumpe el conjuro de otra criatura.',range:'18 m',concentration:false,damage:null,duration:'Instantáneo',cast:'1 reacción'},
    {name:'Relámpago',desc:'Una línea de electricidad atraviesa a todo lo que encuentra a su paso.',range:'Personal (línea de 30 m)',concentration:false,damage:'8d6 eléctrico',duration:'Instantáneo',cast:'1 acción'},
    {name:'Volar',desc:'Otorga velocidad de vuelo a la criatura tocada durante 10 minutos.',range:'Toque',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Restablecimiento Mayor',desc:'Elimina maldiciones, parálisis y reduce características perdidas.',range:'Toque',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Miedo',desc:'Provoca terror en un cono, haciendo que las criaturas huyan aterrorizadas.',range:'Personal (cono de 9 m)',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Muro de Viento',desc:'Un muro de aire feroz bloquea proyectiles y gases.',range:'36 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Velocidad',desc:'Duplica la velocidad, otorga +2 a la CA y una acción extra al objetivo.',range:'9 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Lentitud',desc:'Ralentiza a varias criaturas, reduciendo su velocidad y capacidad de reacción.',range:'36 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Dispersar Magia',desc:'Anula un conjuro o efecto mágico activo.',range:'36 m',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Revivir',desc:'Devuelve a la vida a una criatura muerta hace menos de un minuto.',range:'Toque',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Llamar Relámpagos',desc:'Invoca una tormenta que descarga rayos sobre tus enemigos, turno tras turno.',range:'36 m',concentration:true,damage:'3d10 eléctrico',duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Protección contra Energía',desc:'Otorga resistencia a un tipo de daño elemental elegido.',range:'Toque',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Respirar bajo el Agua',desc:'Permite a varias criaturas respirar bajo el agua durante horas.',range:'9 m',concentration:false,damage:null,duration:'24 horas',cast:'1 acción'},
    {name:'Clarividencia',desc:'Crea un sensor invisible que te permite ver u oír un lugar lejano.',range:'1,6 km',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'10 minutos'},
    {name:'Hablar con los Muertos',desc:'Formulas preguntas a un cadáver, que responde según lo que sabía en vida.',range:'Toque',concentration:false,damage:null,duration:'10 minutos',cast:'1 acción'},
    {name:'Danza Irresistible',desc:'Obliga al objetivo a bailar torpemente, dejándolo vulnerable.',range:'9 m',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Bestia Gigante',desc:'Transforma un animal pequeño en una versión gigante temporal.',range:'Toque',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Luz del Día',desc:'Crea una esfera de luz solar real que disipa oscuridad mágica.',range:'18 m',concentration:false,damage:null,duration:'1 hora',cast:'1 acción'},
    {name:'Puñal Espiritual',desc:'Invoca dagas espectrales flotantes que atacan a tu orden.',range:'Personal (9 m)',concentration:true,damage:'3d4 fuerza',duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Nube Fétida Mayor',desc:'Una niebla pestilente incapacita a quien falle su salvación.',range:'27 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Empalar',desc:'Espinas del suelo se alzan para atravesar y sujetar al objetivo.',range:'18 m',concentration:true,damage:'2d6 perforante',duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Sable Radiante',desc:'Un arma cuerpo a cuerpo brilla y añade daño radiante a sus golpes.',range:'Toque',concentration:true,damage:'2d8 radiante extra por golpe',duration:'Hasta 1 minuto',cast:'1 acción adicional'},
    {name:'Marchitar',desc:'Drena la vitalidad del objetivo, causando daño necrótico y debilidad.',range:'18 m',concentration:false,damage:'4d8 necrótico',duration:'Instantáneo',cast:'1 acción'},
    {name:'Piel Pétrea',desc:'Endurece la piel del objetivo, otorgando resistencia a daño físico.',range:'Toque',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
  ],
  4:[
    {name:'Muro de Fuego',desc:'Crea un muro de llamas que daña a quien lo cruce o esté cerca.',range:'36 m',concentration:true,damage:'5d8 fuego',duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Polimorfar',desc:'Transforma a una criatura en una bestia distinta, con sus estadísticas.',range:'18 m',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Confusión',desc:'Las criaturas en la zona actúan de forma errática e impredecible.',range:'22,5 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Libertad de Movimiento',desc:'El objetivo ignora terreno difícil y no puede quedar apresado ni paralizado.',range:'Toque',concentration:false,damage:null,duration:'1 hora',cast:'1 acción'},
    {name:'Invocar Elemental',desc:'Convoca un espíritu elemental que lucha a tu lado.',range:'27 m',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 minuto'},
    {name:'Ojo Arcano',desc:'Crea un ojo invisible y flotante que puedes mover y ver a través de él.',range:'9 m (el ojo se mueve libremente después)',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Puerta Dimensional',desc:'Te teletransportas instantáneamente a un punto que puedas ver o recordar.',range:'150 m',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Guardián de Fe',desc:'Invoca un espectro protector que golpea a quien se acerque a ti.',range:'9 m',concentration:false,damage:'3d8 radiante',duration:'8 horas (o hasta gastar 60 PG)',cast:'1 acción'},
    {name:'Tormenta de Hielo',desc:'Granizo y hielo golpean una zona, dañando y dificultando el terreno.',range:'90 m',concentration:false,damage:'2d8 contundente + 4d6 frío',duration:'Instantáneo',cast:'1 acción'},
    {name:'Muro de Piedra (menor)',desc:'Levanta una barrera de piedra sólida no mágica que bloquea el paso.',range:'36 m',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Metamorfosis Pétrea (menor)',desc:'Transforma parcialmente al objetivo en piedra, ralentizándolo.',range:'9 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Adivinación Menor',desc:'Consulta un oráculo para obtener una pista breve sobre un evento futuro.',range:'Personal',concentration:false,damage:null,duration:'Instantáneo',cast:'1 minuto'},
    {name:'Convocar Sombras',desc:'Invocas espíritus sombríos que combaten con frío y oscuridad.',range:'18 m',concentration:true,damage:'2d8 frío/necrótico',duration:'Hasta 1 hora',cast:'1 minuto'},
    {name:'Máscara de la Muerte',desc:'Simulas tu propia muerte de forma convincente ante quien te examine.',range:'Toque',concentration:false,damage:null,duration:'1 hora',cast:'1 acción'},
    {name:'Terreno Alucinante',desc:'Transforma la apariencia ilusoria de un terreno, ocultando peligros o creando falsos.',range:'150 m',concentration:false,damage:null,duration:'24 horas',cast:'10 minutos'},
    {name:'Localizar Criatura Mayor',desc:'Sabes la dirección hacia una criatura conocida, incluso a gran distancia.',range:'Personal',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Vínculo entre Compañeros',desc:'Refuerza el lazo mágico con tu familiar o montura, mejorando su resistencia.',range:'Toque',concentration:false,damage:null,duration:'24 horas',cast:'1 acción'},
  ],
  5:[
    {name:'Muro de Fuerza',desc:'Crea una barrera invisible e indestructible que nada físico puede atravesar.',range:'36 m',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Cono de Frío',desc:'Un cono helado congela a todas las criaturas en su área.',range:'Personal (cono de 18 m)',concentration:false,damage:'8d8 frío',duration:'Instantáneo',cast:'1 acción'},
    {name:'Dominar Persona',desc:'Tomas el control mental de un humanoide durante un tiempo prolongado.',range:'18 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Curación en Masa',desc:'Cura a varias criaturas a la vez, repartiendo puntos de golpe entre ellas.',range:'9 m',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Legión de Fantasmas',desc:'Un tropel de figuras espectrales aterra a las criaturas cercanas.',range:'9 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Contactar Otro Plano',desc:'Estableces contacto mental con una entidad de otro plano para hacer preguntas.',range:'Personal',concentration:false,damage:null,duration:'1 minuto',cast:'1 minuto'},
    {name:'Palabra de Poder Aturdir',desc:'Aturdes instantáneamente a una criatura con una sola palabra de poder.',range:'18 m',concentration:false,damage:null,duration:'1 minuto',cast:'1 acción'},
    {name:'Invocar Elemental Mayor',desc:'Convoca un poderoso elemental que lucha por ti durante horas.',range:'27 m',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 minuto'},
    {name:'Telepatía',desc:'Estableces un vínculo mental para comunicarte a larga distancia.',range:'Ilimitado (mismo plano)',concentration:false,damage:null,duration:'1 hora',cast:'1 acción'},
    {name:'Espada Danzante',desc:'Un arma encantada flota y ataca por su cuenta bajo tu control.',range:'36 m',concentration:true,damage:'3d6 cortante',duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Muro de Espinas',desc:'Un seto de zarzas afiladas bloquea el paso y hiere a quien lo cruce.',range:'36 m',concentration:true,damage:'7d8 perforante',duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Antivida',desc:'Un aura repele a los no-muertos, impidiéndoles acercarse o tocarte.',range:'Personal',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Portal Menor',desc:'Abre un pasadizo temporal a un plano cercano o lugar conocido.',range:'3 m',concentration:false,damage:null,duration:'1 ronda',cast:'1 minuto'},
    {name:'Insecto Gigante',desc:'Transforma insectos comunes en versiones gigantes y hostiles.',range:'36 m',concentration:true,damage:null,duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Aniquilación de Muertos Vivientes',desc:'Un estallido de energía radiante castiga con fuerza a los no-muertos cercanos.',range:'Personal (9 m)',concentration:false,damage:'4d8 radiante',duration:'Instantáneo',cast:'1 acción'},
  ],
  6:[
    {name:'Palabra Curativa en Masa',desc:'Cura a distancia a varias criaturas con una sola palabra, sin tocarlas.',range:'18 m',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción adicional'},
    {name:'Globo de Aniquilamiento',desc:'Una esfera de vacío que destruye materia y energía a su paso.',range:'36 m',concentration:false,damage:'10d10 fuerza',duration:'Instantáneo',cast:'1 acción'},
    {name:'Forma Osamenta',desc:'Reanimas huesos de criaturas muertas como sirvientes esqueléticos.',range:'Toque',concentration:false,damage:null,duration:'Instantáneo',cast:'1 minuto'},
    {name:'Alud de Meteoros (menor)',desc:'Fragmentos de roca caen del cielo causando daño de impacto en área.',range:'240 m',concentration:false,damage:'10d6 fuego + 10d6 contundente',duration:'Instantáneo',cast:'1 acción'},
    {name:'Sueño Etéreo',desc:'Duermes profundamente en el plano etéreo, protegido de peligros mundanos.',range:'Personal',concentration:false,damage:null,duration:'8 horas',cast:'1 acción'},
    {name:'Círculo de la Muerte',desc:'Energía negativa masiva mata a criaturas débiles en un radio amplio.',range:'45 m',concentration:false,damage:'8d6 necrótico',duration:'Instantáneo',cast:'1 acción'},
    {name:'Fuerza Draconiana',desc:'Te cubres de escamas espectrales, ganando resistencia y un aliento elemental.',range:'Personal',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción adicional'},
    {name:'Metamorfosis Pétrea',desc:'Convierte por completo al objetivo en estatua de piedra.',range:'18 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Ojo de Águila Verdadera',desc:'Ves la verdadera forma tras ilusiones, transformaciones y disfraces.',range:'Toque',concentration:false,damage:null,duration:'1 hora',cast:'1 acción'},
    {name:'Palabra de Poder Sanar',desc:'Restaura una gran cantidad de puntos de golpe con una sola palabra.',range:'18 m',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Muro de Hielo',desc:'Crea una barrera de hielo sólido que bloquea el paso y el frío daña a quien lo rompe.',range:'36 m',concentration:true,damage:'10d6 frío (al romperse)',duration:'Hasta 10 minutos',cast:'1 acción'},
  ],
  7:[
    {name:'Prisión de las Fuerzas',desc:'Atrapa a una criatura en una celda invisible de energía pura.',range:'18 m',concentration:false,damage:null,duration:'1 hora',cast:'1 acción'},
    {name:'Resurrección',desc:'Devuelve la vida a un muerto, incluso si llevaba tiempo fallecido.',range:'Toque',concentration:false,damage:null,duration:'Instantáneo',cast:'1 hora'},
    {name:'Plaga de Insectos Regeneradora',desc:'Un enjambre persistente hostiga y daña continuamente a los enemigos.',range:'90 m',concentration:true,damage:'4d10 perforante',duration:'Hasta 10 minutos',cast:'1 acción'},
    {name:'Escudo del Odio',desc:'Un aura protectora castiga a quienes ataquen con intenciones malignas.',range:'Personal (3 m)',concentration:false,damage:'4d8 radiante',duration:'1 hora',cast:'1 acción'},
    {name:'Simulacro',desc:'Crea una copia ilusoria pero funcional de una criatura, incluido tú mismo.',range:'Toque',concentration:false,damage:null,duration:'Hasta que se disipa',cast:'12 horas'},
    {name:'Teletransporte',desc:'Traslada instantáneamente a un grupo a un destino lejano y conocido.',range:'Toque',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Espada de Fuego Feérico',desc:'Invoca un arma feérica flamígera con propiedades encantadas.',range:'Toque',concentration:false,damage:'4d6 fuego',duration:'1 hora',cast:'1 acción adicional'},
    {name:'Regenerar',desc:'Restaura miembros perdidos y cura heridas graves de forma prolongada.',range:'Toque',concentration:false,damage:null,duration:'1 hora',cast:'1 minuto'},
  ],
  8:[
    {name:'Dominar Monstruo',desc:'Controlas mentalmente a cualquier criatura, sin importar su naturaleza.',range:'18 m',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Tormenta de Fuego Incandescente',desc:'Columnas de fuego brotan del suelo, arrasando una zona amplia.',range:'36 m',concentration:true,damage:'10d8 fuego',duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Clon',desc:'Crea un cuerpo de repuesto que recibe tu alma si mueres.',range:'Toque',concentration:false,damage:null,duration:'Instantáneo (permanente)',cast:'1 hora'},
    {name:'Antimagia Total',desc:'Suprime toda magia dentro de una esfera a tu alrededor.',range:'Personal (3 m)',concentration:true,damage:null,duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Ira de la Naturaleza',desc:'El entorno natural cobra vida para atacar a tus enemigos.',range:'36 m',concentration:true,damage:'3d6 contundente',duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Maremoto',desc:'Invocas una ola gigante que arrasa y arrastra todo a su paso.',range:'500 m',concentration:true,damage:'6d10 contundente',duration:'Hasta 6 asaltos',cast:'1 minuto'},
  ],
  9:[
    {name:'Deseo',desc:'El conjuro más poderoso: puede replicar cualquier otro o alterar la realidad, con riesgo.',range:'Personal',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Meteoros',desc:'Bólidos de fuego caen del cielo devastando una zona enorme.',range:'1,6 km',concentration:false,damage:'20d6 fuego + 20d6 contundente',duration:'Instantáneo',cast:'1 acción'},
    {name:'Curación Verdadera',desc:'Cura por completo, elimina ceguera, sordera y maldiciones de una vez.',range:'Toque',concentration:false,damage:null,duration:'Instantáneo',cast:'1 acción'},
    {name:'Resurrección Verdadera',desc:'Devuelve la vida incluso sin restos del cuerpo original.',range:'Toque',concentration:false,damage:null,duration:'Instantáneo',cast:'1 hora'},
    {name:'Portal Mayor',desc:'Abre un portal estable entre dos planos o lugares distantes.',range:'18 m',concentration:true,damage:null,duration:'Hasta 1 minuto',cast:'1 acción'},
    {name:'Tormenta de Venganza',desc:'Una tormenta cataclísmica azota un área con vientos, rayos y granizo.',range:'1,6 km',concentration:true,damage:'Variable por asalto (hasta 10d6)',duration:'Hasta 1 hora',cast:'1 acción'},
    {name:'Prisión Astral',desc:'Destierra a una criatura a una prisión extradimensional casi inescapable.',range:'9 m',concentration:false,damage:null,duration:'Hasta que se disipa',cast:'1 minuto'},
  ],
};

/* ---------- OFICIOS (para PNJs) ---------- */
const OFICIOS = [
  {id:'herrero', name:'Herrero', priority:['str','con','wis'], hitDie:8, shop:'armeria', armorHint:'cuero + delantal (11+DES)', weaponHint:'martillo de guerra'},
  {id:'alquimista', name:'Alquimista / Boticario', priority:['int','wis','dex'], hitDie:6, shop:'pociones', armorHint:'ropa (10+DES)', weaponHint:'daga'},
  {id:'sacerdote', name:'Sacerdote / Clériga', priority:['wis','cha','con'], hitDie:8, shop:'templo', armorHint:'cota de escamas (14+DESmax2)', weaponHint:'maza'},
  {id:'mercader', name:'Mercader General', priority:['cha','int','wis'], hitDie:8, shop:'general', armorHint:'ropa (10+DES)', weaponHint:'bastón'},
  {id:'tabernero', name:'Posadero / Tabernero', priority:['cha','con','wis'], hitDie:8, shop:null, armorHint:'ropa (10+DES)', weaponHint:'garrote'},
  {id:'guardia', name:'Guardia', priority:['str','con','dex'], hitDie:10, shop:null, armorHint:'cota de malla (16)', weaponHint:'lanza'},
  {id:'erudito', name:'Erudito / Bibliotecario', priority:['int','wis','cha'], hitDie:6, shop:'pergaminos', armorHint:'ropa (10+DES)', weaponHint:'daga'},
  {id:'encantador', name:'Encantador (tienda mágica)', priority:['int','cha','wis'], hitDie:6, shop:'magico', armorHint:'ropa (10+DES)', weaponHint:'vara'},
  {id:'herborista', name:'Herborista / Curandero', priority:['wis','int','con'], hitDie:8, shop:'herbolario', armorHint:'ropa (10+DES)', weaponHint:'cayado'},
  {id:'joyero', name:'Joyero', priority:['int','dex','cha'], hitDie:6, shop:'joyeria', armorHint:'ropa (10+DES)', weaponHint:'daga'},
  {id:'granjero', name:'Granjero', priority:['str','con','wis'], hitDie:8, shop:null, armorHint:'ropa (10+DES)', weaponHint:'horca'},
  {id:'cazador', name:'Cazador / Trampero', priority:['dex','wis','con'], hitDie:8, shop:'pieles', armorHint:'cuero (11+DES)', weaponHint:'arco largo'},
  {id:'marinero', name:'Marinero', priority:['str','dex','con'], hitDie:8, shop:null, armorHint:'ropa (10+DES)', weaponHint:'cimitarra'},
  {id:'ladron', name:'Ladrón / Contrabandista', priority:['dex','int','cha'], hitDie:8, shop:'mercadonegro', armorHint:'cuero (11+DES)', weaponHint:'daga'},
  {id:'noble', name:'Noble', priority:['cha','int','wis'], hitDie:8, shop:null, armorHint:'ropa fina (10+DES)', weaponHint:'estoque'},
  {id:'sastre', name:'Sastre / Artesano', priority:['dex','int','cha'], hitDie:6, shop:'ropa', armorHint:'ropa (10+DES)', weaponHint:'tijeras (daga)'},
];

/* ---------- SHOP INVENTORY POOLS by tier (party level) ---------- */
const SHOPMUNDANE = {
  armeria:[['Espada larga','15 po'],['Hacha de mano','5 po'],['Cota de malla','75 po'],['Escudo','10 po'],['Yelmo de acero','—'],['20 flechas','1 po'],['Herraduras','2 po']],
  pociones:[['Poción de curación (2d4+2)','50 po'],['Antitóxico','50 po'],['Aceite','1 po'],['Vial vacío','1 po'],['Componentes de alquimia (kit)','50 po']],
  templo:[['Símbolo sagrado','5 po'],['Incienso bendito','1 po'],['Poción de curación','50 po'],['Aceite santo','25 po'],['Kit de sanador','5 po']],
  general:[['Ración de viaje (x5)','2.5 po'],['Cuerda de cáñamo 15m','1 po'],['Mochila','2 po'],['Antorcha (x5)','0.5 po'],['Saco de dormir','1 po'],['Yesca y pedernal','0.5 po']],
  pergaminos:[['Pergamino en blanco','10 po'],['Tinta y pluma','12 po'],['Libro','25 po'],['Mapa local','5 po']],
  magico:[['Componentes arcanos raros','variable'],['Foco arcano','10-20 po']],
  herbolario:[['Kit de herbolario','5 po'],['Hierbas curativas','2 po'],['Ungüento contra quemaduras','8 po']],
  joyeria:[['Anillo de plata','10 po'],['Gema pulida','25-100 po'],['Engaste de joyero (servicio)','variable']],
  pieles:[['Piel curtida','3-8 po'],['Cuerda para trampas','1 po'],['Cebo','1 po']],
  mercadonegro:[['Ganzúas','25 po (calidad dudosa)'],['«Mercancía sin preguntas»','negociable'],['Disfraz','7 po']],
  ropa:[['Traje sencillo','5 po'],['Traje fino','15 po'],['Capa de viaje','2 po']],
};

/* magic item pools by rarity, tagged to shop types */
const MAGICPOOL = {
  common:{
    pociones:['Poción de curación','Poción de escalada','Poción de resistencia al ácido','Poción de aliento de agua','Poción de trepar como araña (menor)','Aceite de afilado','Poción de resistencia al frío','Tónico de resistencia menor'],
    armeria:['Arma +0 con grabado élfico (decorativa)','Munición +1 (lote pequeño)','Piedra de afilar encantada','Correa de sujeción reforzada'],
    magico:['Ilusionista de Bolsillo (chuchería)','Vela de vigilia','Cerillas eternas','Tinta luminosa','Baraja ilusoria'],
    herbolario:['Ungüento de curación menor','Cataplasma de resistencia al veneno','Incienso calmante','Té de sanación ligera'],
    templo:['Vela de la Iglesia (protección menor)','Poción de curación','Rosario bendito','Agua bendita (vial)'],
    pergaminos:['Pergamino de conjuro de nivel 1','Tinta que brilla al conjurar'],
    joyeria:['Anillo de latón con runa menor','Amuleto de buena suerte (cosmético)','Broche que no se pierde'],
    pieles:['Capa de camuflaje ligero','Guantes que no resbalan'],
    ropa:['Capa que repele el polvo','Botas silenciosas (leve)'],
    general:['Mochila que nunca se moja por dentro','Cantimplora que enfría el agua'],
    mercadonegro:['Llave maestra chapucera','Polvo para borrar huellas'],
  },
  uncommon:{
    pociones:['Poción de curación mayor','Poción de aliento de fuego','Poción de resistencia al fuego','Poción de invisibilidad','Poción de crecimiento/reducción','Poción de trepar como araña','Poción de agallas (respirar bajo el agua)','Poción de valentía líquida'],
    armeria:['Arma +1','Armadura +1','Munición +1','Escudo centinela'],
    magico:['Bolsa devoradora (¡cuidado!)','Capa élfica','Botas de zancada y salto','Guantes de destreza','Vara del pícaro','Lentes de lectura mágica'],
    pergaminos:['Pergamino de conjuro de nivel 2','Pergamino de protección','Libro de conjuros parcialmente encantado'],
    joyeria:['Amuleto de salud','Anillo de calidez','Broche del escudo','Gargantilla de resistencia menor'],
    herbolario:['Antitóxico superior','Cataplasma de curación mayor','Bálsamo contra parálisis'],
    templo:['Poción de curación mayor','Talismán de la fe','Incensario de purificación'],
    pieles:['Capa de elfo de los bosques','Botas de rastreo silencioso'],
    ropa:['Capa de resistencia al clima','Sombrero de disfraces'],
    general:['Bolsa de contención (pequeña)','Cuerda de escalador'],
    mercadonegro:['Ganzúas de maestro','Polvo de invisibilidad breve'],
  },
  rare:{
    pociones:['Poción de curación suprema','Poción de velocidad','Poción de forma gaseosa','Poción de fuerza de gigante de colina','Poción de clarividencia líquida','Elixir de resistencia a la muerte (menor)'],
    armeria:['Arma +2','Armadura +2','Escudo +1','Ballesta del francotirador'],
    magico:['Vara de las Maravillas Menor','Anillo de protección','Manto de resistencia','Bastón de mando (menor)','Guantelete de fuerza del ogro'],
    pergaminos:['Pergamino de conjuro de nivel 4-5','Tomo de erudición','Libro de conjuros con guardián arcano'],
    joyeria:['Ojo de Águila (gema encantada)','Anillo de sigilo','Diadema de percepción'],
    templo:['Bastón sagrado (menor)','Reliquia curativa','Escudo bendito de fe'],
    pieles:['Capa de la sombra','Botas de las siete leguas (menor)'],
    ropa:['Capa de protección','Guantes del artesano maestro'],
    general:['Bolsa de contención','Farol de la verdad'],
    mercadonegro:['Anillo de fuga','Máscara del rostro cambiante'],
  },
  veryrare:{
    pociones:['Poción de curación suprema (varias)','Poción de invulnerabilidad','Elixir de gigante de tormenta','Filtro de deseos (menor)'],
    armeria:['Arma +3','Armadura +3','Escudo del guardián'],
    magico:['Bola de cristal','Alfombra voladora (pequeña)','Cuerno de invocación (menor)'],
    pergaminos:['Pergamino de conjuro de nivel 6-8','Grimorio prohibido'],
    templo:['Báculo de curación','Reliquia de resurrección menor'],
    joyeria:['Anillo de los tres deseos (agotado en dos)','Corona de intelecto'],
    pieles:['Manto del dragón menor','Capa de invisibilidad parcial'],
  },
  legendary:{
    pociones:['Elixir de la vida eterna (dosis única)','Poción de curación legendaria'],
    armeria:['Arma +3 con sensibilidad (inteligente)','Armadura de leyenda'],
    magico:['Vara de las Siete Partes (fragmento)','Anillo de los Tres Deseos (intacto)','Bastón del Archimago (menor)'],
    pergaminos:['Tomo de las Fuerzas Claras/Oscuras','Pergamino del conjuro Deseo'],
    templo:['Reliquia de resurrección verdadera','Báculo de la vida'],
    joyeria:['Corona de un rey caído','Gema del alma cautiva'],
  },
};

/* ---------- CR TABLE (2024 DMG-style guide, AC/HP/Attack/Damage/DC by CR) ---------- */
const CRTABLE = [
  {cr:'0',   crn:0,    prof:2, ac:13, hp:[1,6],     atk:3,  dmg:[0,1],    dc:13, xp:10},
  {cr:'1/8', crn:0.125,prof:2, ac:13, hp:[7,35],    atk:3,  dmg:[2,3],    dc:13, xp:25},
  {cr:'1/4', crn:0.25, prof:2, ac:13, hp:[36,49],   atk:3,  dmg:[4,5],    dc:13, xp:50},
  {cr:'1/2', crn:0.5,  prof:2, ac:13, hp:[50,70],   atk:3,  dmg:[6,8],    dc:13, xp:100},
  {cr:'1',   crn:1,    prof:2, ac:13, hp:[71,85],   atk:3,  dmg:[9,14],   dc:13, xp:200},
  {cr:'2',   crn:2,    prof:2, ac:13, hp:[86,100],  atk:3,  dmg:[15,20],  dc:13, xp:450},
  {cr:'3',   crn:3,    prof:2, ac:13, hp:[101,115], atk:4,  dmg:[21,26],  dc:13, xp:700},
  {cr:'4',   crn:4,    prof:2, ac:14, hp:[116,130], atk:5,  dmg:[27,32],  dc:14, xp:1100},
  {cr:'5',   crn:5,    prof:3, ac:15, hp:[131,145], atk:6,  dmg:[33,38],  dc:15, xp:1800},
  {cr:'6',   crn:6,    prof:3, ac:15, hp:[146,160], atk:6,  dmg:[39,44],  dc:15, xp:2300},
  {cr:'7',   crn:7,    prof:3, ac:15, hp:[161,175], atk:6,  dmg:[45,50],  dc:15, xp:2900},
  {cr:'8',   crn:8,    prof:3, ac:16, hp:[176,190], atk:7,  dmg:[51,56],  dc:16, xp:3900},
  {cr:'9',   crn:9,    prof:4, ac:16, hp:[191,205], atk:7,  dmg:[57,62],  dc:16, xp:5000},
  {cr:'10',  crn:10,   prof:4, ac:17, hp:[206,220], atk:7,  dmg:[63,68],  dc:16, xp:5900},
  {cr:'11',  crn:11,   prof:4, ac:17, hp:[221,235], atk:8,  dmg:[69,74],  dc:17, xp:7200},
  {cr:'12',  crn:12,   prof:4, ac:17, hp:[236,250], atk:8,  dmg:[75,80],  dc:17, xp:8400},
  {cr:'13',  crn:13,   prof:5, ac:18, hp:[251,265], atk:8,  dmg:[81,86],  dc:18, xp:10000},
  {cr:'14',  crn:14,   prof:5, ac:18, hp:[266,280], atk:8,  dmg:[87,92],  dc:18, xp:11500},
  {cr:'15',  crn:15,   prof:5, ac:18, hp:[281,295], atk:8,  dmg:[93,98],  dc:18, xp:13000},
  {cr:'16',  crn:16,   prof:5, ac:18, hp:[296,310], atk:9,  dmg:[99,104], dc:18, xp:15000},
  {cr:'17',  crn:17,   prof:6, ac:19, hp:[311,325], atk:10, dmg:[105,110],dc:19, xp:18000},
  {cr:'18',  crn:18,   prof:6, ac:19, hp:[326,340], atk:10, dmg:[111,116],dc:19, xp:20000},
  {cr:'19',  crn:19,   prof:6, ac:19, hp:[341,355], atk:10, dmg:[117,122],dc:19, xp:22000},
  {cr:'20',  crn:20,   prof:6, ac:19, hp:[356,400], atk:10, dmg:[123,140],dc:19, xp:25000},
  {cr:'21',  crn:21,   prof:7, ac:19, hp:[401,445], atk:11, dmg:[141,158],dc:20, xp:33000},
  {cr:'22',  crn:22,   prof:7, ac:19, hp:[446,490], atk:11, dmg:[159,176],dc:20, xp:41000},
  {cr:'24',  crn:24,   prof:7, ac:19, hp:[536,580], atk:12, dmg:[195,212],dc:21, xp:62000},
];

const XPTHRESHOLDS = { //  easy, medium, hard, deadly
  1:[25,50,75,100], 2:[50,100,150,200], 3:[75,150,225,400], 4:[125,250,375,500],
  5:[250,500,750,1100], 6:[300,600,900,1400], 7:[350,750,1100,1700], 8:[450,900,1400,2100],
  9:[550,1100,1600,2400], 10:[600,1200,1900,2800], 11:[800,1600,2400,3600], 12:[1000,2000,3000,4500],
  13:[1100,2200,3400,5100], 14:[1250,2500,3800,5700], 15:[1400,2800,4300,6400], 16:[1600,3200,4800,7200],
  17:[2000,3900,5900,8800], 18:[2100,4200,6300,9500], 19:[2400,4900,7300,10900], 20:[2800,5700,8500,12700],
};


const MONSTERS = [
  {id:'goblin', name:'Trasgo', type:'Humanoide diminuto (goblinoide)', cr:'1/4', traits:['Fuga Ágil (retirada como bonus)'], attackName:'Cimitarra / Arco corto'},
  {id:'orco', name:'Orco', type:'Humanoide mediano', cr:'1/2', traits:['Agresivo (moverse hacia enemigo como bonus)'], attackName:'Hacha de guerra'},
  {id:'lobo', name:'Lobo', type:'Bestia mediana', cr:'1/4', traits:['Táctica de manada (ventaja si aliado cerca)'], attackName:'Mordisco'},
  {id:'oso', name:'Oso pardo', type:'Bestia grande', cr:'1', traits:['Olfato y oído agudos'], attackName:'Garra / Mordisco'},
  {id:'ogro', name:'Ogro', type:'Gigante grande', cr:'2', traits:['Fuerza bruta'], attackName:'Garrote'},
  {id:'esqueleto', name:'Esqueleto', type:'No-muerto mediano', cr:'1/4', traits:['Vulnerable a contundente','Inmune a veneno'], attackName:'Espada corta / Arco'},
  {id:'zombi', name:'Zombi', type:'No-muerto mediano', cr:'1/4', traits:['Fortaleza de no-muerto'], attackName:'Puñetazo'},
  {id:'ghoul', name:'Necrófago (Ghoul)', type:'No-muerto mediano', cr:'1', traits:['Garra paralizante'], attackName:'Mordisco / Garras'},
  {id:'ogromago', name:'Ogromago', type:'Gigante mediano (hechicero)', cr:'5', traits:['Invisibilidad a voluntad','Conjuros menores'], attackName:'Espada larga / Conjuro'},
  {id:'troll', name:'Trol', type:'Gigante grande', cr:'5', traits:['Regeneración','Vulnerable a fuego/ácido'], attackName:'Mordisco / Garras'},
  {id:'aranagigante', name:'Araña gigante', type:'Bestia grande', cr:'1', traits:['Veneno','Telaraña'], attackName:'Mordisco'},
  {id:'owlbear', name:'Ozobú (Owlbear)', type:'Monstruosidad grande', cr:'3', traits:['Olfato y oído agudos'], attackName:'Pico / Garras'},
  {id:'draconoide', name:'Dracoborn (guardia de dragón)', type:'Humanoide mediano', cr:'2', traits:['Resistencia elemental'], attackName:'Glaive'},
  {id:'hechicerooscuro', name:'Cultista Oscuro', type:'Humanoide mediano (conjurador)', cr:'2', traits:['Conjuros menores de necromancia'], attackName:'Daga / Conjuro'},
  {id:'elemental', name:'Elemental de Fuego', type:'Elemental grande', cr:'5', traits:['Forma de fuego','Prende fuego al contacto'], attackName:'Toque'},
  {id:'gigantecolina', name:'Gigante de las colinas', type:'Gigante enorme', cr:'5', traits:['Fuerza descomunal'], attackName:'Garrote'},
  {id:'mindflayer', name:'Devorador de Mentes', type:'Aberración mediana', cr:'7', traits:['Extracción de cerebro','Velo psiónico'], attackName:'Tentáculos'},
  {id:'vampiro', name:'Vampiro Espectral', type:'No-muerto mediano', cr:'8', traits:['Regeneración','Forma de niebla','Drenaje de vida'], attackName:'Garras / Mordisco'},
  {id:'dragonjoven', name:'Dragón joven', type:'Dragón grande', cr:'8', traits:['Aliento elemental','Resistencia a legendarios (opcional)'], attackName:'Mordisco / Garras / Aliento'},
  {id:'liche', name:'Liche', type:'No-muerto mediano (conjurador supremo)', cr:'21', traits:['Conjuros de alto nivel','Filacteria (renace)'], attackName:'Toque paralizante / Conjuro'},
];


/* ---------- name generator ---------- */

const DIFFINDEX = {
  easy: 0,
  medium: 1,
  hard: 2,
  deadly: 3
};

const STARTINGGEAR = {
  barbaro: ['Arma simple', '4 jabalinas', 'Explorador de viaje'],
  bardo: ['Instrumento musical', 'Daga', 'Ropa fina'],
  clerigo: ['Símbolo sagrado', 'Maza', 'Cota ligera o media'],
  druida: ['Armadura ligera no metálica', 'Cayado', 'Kit herbal'],
  guerrero: ['Armadura inicial', 'Arma marcial', 'Escudo si procede'],
  monje: ['Arma monástica', 'Pack de viaje', 'Ropa sencilla'],
  paladin: ['Armadura pesada o media', 'Escudo', 'Arma marcial'],
  explorador: ['Armadura media', 'Arco o armas a elegir', 'Pack de explorador'],
  picaro: ['Arma fina', 'Herramientas de ladrón', 'Equipo de sigilo'],
  hechicero: ['Foco arcano', 'Daga', 'Pack de explorador'],
  brujo: ['Foco arcano', 'Arma ligera', 'Pack de aventurero'],
  mago: ['Libro de conjuros', 'Daga', 'Tinta, pluma y pergamino']
};

const NAMESYLSTART = ['Ael', 'Bel', 'Cor', 'Dar', 'El', 'Fen', 'Gal', 'Har', 'Ith', 'Jor', 'Kel', 'Lar', 'Mor', 'Nor', 'Or', 'Per', 'Quel', 'Rin', 'Sar', 'Tor', 'Ur', 'Val', 'Wen', 'Xan', 'Yor', 'Zel'];
const NAMESYLMID = ['a', 'e', 'i', 'o', 'u', 'ae', 'ia', 'ou', 'ar', 'er', 'ir', 'or', 'ur'];
const NAMESYLEND = ['dor', 'en', 'ion', 'ar', 'or', 'an', 'el', 'is', 'us', 'ath', 'im', 'or', 'yn', 'as'];

const RANDOMADJ = ['Oscuro', 'Roto', 'Verdadero', 'Ágil', 'Férreo', 'Siniestro', 'Antiguo', 'Hambriento', 'Silente', 'Voraz'];
const RANDOMNOUN = ['Filo', 'Umbral', 'Eco', 'Cuervo', 'Brasero', 'Vigía', 'Sello', 'Abismo', 'Llama', 'Lobo'];
const RANDOMTYPES = ['Bestia', 'No muerto', 'Constructo', 'Monstruosidad', 'Aberración', 'Humanoide', 'Fienda', 'Gigante'];